### ISSUE TITLE
This is my favorite mod and I would love for it to update!

### ISSUE THREAD

**Issue by OverlordGoose** [Ran-Mewo/UwU#3]
Hello! I saw in another thread on this GitHub about 1.19 versions, and I saw that you said you already had the 1.19.2 version, but were about to release it when Mojang updated the chat system. Well I'm starting a 1.19.2 server, and really wanted this mod in it, so I was wondering if you could release the version if you have it, or otherwise backport as soon as possible? 
Thanks!

**Comment by Ran-Mewo** [comment]
I forgor
I'll update soon I promise!

**Comment by Ran-Mewo** [comment]
It's done https://modrinth.com/mod/uwuifier/version/TXZYuDMs
