### ISSUE TITLE
This mod has everything I need for my dreams to come true, it's just missing one thing...(1.19.2 pweass)

### ISSUE THREAD

**Issue by eygaYO** [Ran-Mewo/UwU#4]
Hewwo thewe! I'm lookin' for a mod to help me achiev my minecwaftin' dreams, and evewything I need is wight in this mod!! Unfowtunatewy, the version i play on is 1.19.2, and the mod ov my dweams is only avawible on 1.19.3. (⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄) I was wookin' thwough the issues when i saw that a vewsion for was 1.19.2 was actually weady! THIS MAKED ME SOO EXCITED!!!!! ( ˘⌣˘) PWEESE PWELSE PLSPLSPLS REWEASE THE 1.19.2 VERSION ASAPPP!!!☆*:・ﾟ TYSMMMMMM (o^▽^o)

ohhh yuuma...i'll finally see you in minecraft soon...

**Comment by Ran-Mewo** [comment]
I forgor
I'll update soon I promise!

**Comment by Ran-Mewo** [comment]
Done (sorry for taking so long ehe~) https://modrinth.com/mod/uwuifier/version/TXZYuDMs

**Comment by eygaYO** [comment]
Thank u so much <3
